
import Head from 'next/head';
import Image from 'next/image';
import poza from './images/poza_profil.jpg';
import mancode from './images/developer.png';
import aboutme from './images/about_me.png';
import web1 from './images/web1.png';
import web2 from './images/web2.png';
import web3 from './images/web3.png';
import web4 from './images/web4.png';
import {BsFillMoonStarsFill, BsDiscord} from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiOutlineLink} from 'react-icons/ai'
import { SiJavascript, SiHtml5,
         SiCss3, SiReact, 
         SiNodedotjs, SiGithub} from 'react-icons/si'
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nastase Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gradient-to-r from-gray-900 via-indigo-900 to-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-tour font-bold dark:text-white">PORTOFOLIO</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white"/>
            </li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href='https://pdfhost.io/v/a04I04NcO_resume'> <b>Resume</b> </a></li>
          </ul>
          </nav>
          <div className="text-center p-10 dark:text-white">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl "><b>Nastase Valentin</b></h2>
            <h3 className="text-md py-5 leading-8 text-grey-800 md:text-xl max-w-xl mx-auto ">FrontEnd Developer</h3>
            <p><i>“Everyone in this country should learn how to program because it teaches you how to think” – Steve Jobs.</i></p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 font-medium md:text-6xl dark:text-white">
            <a href="https://www.discordapp.com/users/485149099025498117">
             <BsDiscord />
            </a> 
            <a href="https://github.com/V4L3N7Y">
             <AiFillGithub/>
            </a> 
            <a href="https://www.linkedin.com/in/valentin-n%C4%83stase-509b811ba/">
             <AiFillLinkedin/>
            </a>
          </div>
          
            <div className="relative mx-auto overflow-hidden rounded-full bg-gray-600 w-60 h-70 lg:w-80 mt-20 ">
              <Image src={poza}/>
            </div>
          
        </section>
        {/* section two */}

        <section >
          <div>
            <h3 className="text-3xl text-center py-5 dark:text-white"><b>Hello World</b></h3>
            <p className="text-md text-center mx-auto py-2 max-w-4xl leading-8 text-gray-800 dark:text-white">
            I am a driven individual with a strong desire for personal and professional growth, fueled by my passion for coding and problem-solving.
            My sense of humor helps keep things light and enjoyable in the workplace.
            </p>
          </div>
          <div className="lg:flex justify-around gap-10 mx-auto">
            <div className="text-center rounded-lg bg-slate-100 shadow-xl p-10 my-10 dark:bg-gray-900">
              <Image src={mancode} height={100} width={200} className="mx-auto"/>
              <hr/>
              <h3 className="text-2xl font-medium pt-8 pb-2 dark:text-white"><b>Skills</b></h3>
              <div className='text-lg grid text-neutral-500 grid-cols-2 justify-center gap-16 py-3  font-medium md:text-6xl dark:text-white'>
             
               <a className="dark:text-white">
                <SiHtml5 className='h-10 w-10 mx-auto'/>
                <p className='text-4xl'>Html</p>
               </a> 
               <a className="dark:text-white">
                <SiJavascript className='h-10 w-10 mx-auto'/>
                <p className='text-3xl'>Javascript</p>
               </a> 
                
               <a className="dark:text-white">
               <SiCss3 className='h-10 w-10 mx-auto'/>
                <p className='text-4xl'>Css3</p>
               </a> 
                
               <a className="dark:text-white">
                <SiReact className='h-10 w-10 mx-auto'/>
                <p className='text-4xl'>React</p>
               </a>

               <a className="dark:text-white">
                <SiNodedotjs className='h-10 w-10 mx-auto'/>
                <p className='text-4xl'>Node.js</p>
               </a>

               <a className="dark:text-white">
                <SiGithub className='h-10 w-10 mx-auto'/>
                <p className='text-4xl'>Github</p>
               </a>

              </div> 
            </div>

            <div className="text-center rounded-lg bg-slate-100 shadow-xl p-10 my-10 dark:bg-gray-900">
              <Image src={aboutme} height={100} width={200} className=" shadow-xl overflow-hidden rounded-full mx-auto"/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white"><b>About Me</b></h3>
              <hr/>
              <p className="py-2 dark:text-white mx-auto max-w-sm" >I am a motivated and passionate software developer with a strong desire to learn and grow in my field.
                                                              I have been coding for 1 and a half years, and I am constantly looking for new challenges and opportunities to improve my skills.
                                                              In my free time, I enjoy listening to music and playing the piano and cooking. I also love spending time outdoors, whether it's going for a walk or a hike.</p>
              <p className="py-2 dark:text-white  mx-auto max-w-sm" >I am always looking for ways to further my personal growth, whether it's through learning new technologies or picking up new hobbies.
                                                              I believe that personal growth is essential for professional development, and I am dedicated to continually learning and improving.</p>
               <hr/>
            </div>
          </div>
        

        {/* section three */}
         
         <div className='text-center'>
           <h3 className="text-3xl py-1 mx-auto dark:text-white"><b>PROJECTS</b></h3>

           <p className="text-md py-2 pb-10 leading-8 text-gray-800 dark:text-white">
             [Below are my projects. Please take a look:]  
           </p>

         </div>


        <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/2 flex-1">
            <Image src={web1}  className="hover:shadow-[0_35px_60px_-15px_rgba(0,255,255)] rounded-lg object-cover" width={'100%'} height={'100%'} />
           <div className='flex flex-row mt-10 justify-center gap-10 dark:text-white'>
            <a href='https://github.com/V4L3N7Y/OnlineShop'>
             <AiFillGithub className='w-10 h-10'/>
            </a> 
            <a href="https://vali-onlineshop.netlify.app">
             <AiOutlineLink className='w-10 h-10'/>
            </a> 
            </div>
          </div>

          <div className="basis-1/2 flex-1">
            <Image src={web2} className="hover:shadow-[0_35px_60px_-15px_rgba(0,255,255)] rounded-lg object-cover" width={'100%'} height={'100%'} />
            <div className='flex flex-row mt-10 justify-center gap-10 dark:text-white'>
            <a href="https://github.com/V4L3N7Y/Quiz-Game">
             <AiFillGithub className='w-10 h-10'/>
            </a> 
            <a href="https://vali-quiz.netlify.app">
             <AiOutlineLink className='w-10 h-10'/>
            </a> 
            </div>
          </div>

          <div className="basis-1/2 flex-1">
            <Image src={web3} className="hover:shadow-[0_35px_60px_-15px_rgba(0,255,255)] rounded-lg object-cover" width={'100%'} height={'100%'} />
            <div className='flex flex-row mt-10 justify-center gap-10 dark:text-white'>
            <a href="https://github.com/V4L3N7Y/Exp-Tracker">
             <AiFillGithub className='w-10 h-10'/>
            </a> 
            <a href="https://vali-exp-tracker.netlify.app">
             <AiOutlineLink className='w-10 h-10'/>
            </a> 
            </div> 
          </div>

          <div className="basis-1/2 flex-1">
            <Image src={web4} className="hover:shadow-[0_35px_60px_-15px_rgba(0,255,255)] rounded-lg object-cover" width={'100%'} height={'100%'} />
            <div className='flex flex-row mt-10 mb-10 justify-center gap-10 dark:text-white'>
            <a href="https://github.com/V4L3N7Y/3CardColumnCssFront">
             <AiFillGithub className='w-10 h-10'/>
            </a> 
            <a href="https://3columscards.netlify.app">
             <AiOutlineLink className='w-10 h-10'/>
            </a> 
            </div> 
          </div>
        </div> 
         </section>
      </main>

      <footer class="p-4 bg-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-900">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/" class="hover:underline">Valentin™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
       <form action="mailto:you@yourwebsite.com">
          <li>
             <a href="#" action="mailto:you@yourwebsite.com" class="hover:underline">Contact</a>
          </li>
       </form>    
    </ul>
</footer> 

    </div>
  )
}
