import Head from 'next/head';
import Image from 'next/image';
import poza from './images/poza_profil.jpg';
import mancode from './images/developer.png';
import aboutme from './images/about_me.png';
import web1 from './images/web1.png';
import web2 from './images/web2.png';
import web3 from './images/web3.png';
import web4 from './images/web4.png';
import {BsFillMoonStarsFill, BsDiscord} from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import styles from '../styles/Home.module.css';
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nastase Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons dark:text-white">PORTOFOLIO</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
            </li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
          </ul>
          </nav>
          <div className="text-center p-10 dark:text-white">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl ">Nastase Valentin</h2>
            <h3 className="text-md py-5 leading-8 text-grey-800 md:text-xl max-w-xl mx-auto ">FrontEnd Developer</h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 font-medium md:text-6xl dark:text-white">
            <BsDiscord/>
            <AiFillGithub/>
            <AiFillLinkedin/>
          </div>
          
            <div className="relative mx-auto overflow-hidden rounded-full bg-gray-600 w-60 h-70 lg:w-80 mt-20 ">
              <Image src={poza}/>
            </div>
          
        </section>
        {/* section two */}

        <section>
          <div>
            <h3 className="text-3xl text-center py-5">Hakuna Matata</h3>
            <p className="text-md text-center py-2 leading-8 text-gray-80">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
            </p>
            <p className="text-md text-center py-2 leading-8 text-gray-800">Contrary to popular belief, Lorem Ipsum is not simply random text</p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center rounded-lg bg-slate-100 shadow-xl p-10 my-10 dark:bg-gray-700">
              <Image src={mancode} height={100} width={200} className=" mx-auto"/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">My Projects</h3>
              <p className="py-2 dark:text-white">Creating personal projects to show my abilities in the modern world in technology</p>
              <h4 className="p4 text-teal-600">This is what i know </h4>
              <p className="text-gray-800 py-1 dark:text-white">Html & Css</p>
              <p className="text-gray-800 py-1 dark:text-white">Javascript & Node.js</p>
              <p className="text-gray-800 py-1 dark:text-white">Bootstrap & Photoshop</p>
            </div>

            <div className="text-center rounded-lg bg-slate-100 shadow-xl p-10 my-10 dark:bg-gray-700">
              <Image src={aboutme} height={100} width={200} className=" shadow-xl overflow-hidden rounded-full mx-auto"/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">My Projects</h3>
              <p className="py-2 dark:text-white">Creating personal projects to show my abilities in the modern world in technology</p>
              <h4 className="p4 text-teal-600 ">This is what i know </h4>
              <p className="text-gray-800 py-1 dark:text-white">Html & Css</p>
              <p className="text-gray-800 py-1 dark:text-white">Javascript & Node.js</p>
              <p className="text-gray-800 py-1 dark:text-white">Bootstrap & Photoshop</p>
            </div>
          </div>
        

        {/* section three */}
         
         <div>
           <h3 className="text-3xl py-1 dark:text-white">Portofolio</h3>

           <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
             Contrary to popular belief, Lorem Ipsum is not simply random text. 
              It has roots in a piece of classical Latin literature from 45 BC
           </p>

           <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
             Contrary to popular belief, Lorem Ipsum is not simply random text. 
              It has roots in a piece of classical Latin literature from 45 BC
            </p>
         </div>


        <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/2 flex-1">
            <Image src={web1}  className=" rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>

          <div className="basis-1/2 flex-1">
            <Image src={web2} className=" rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>

          <div className="basis-1/2 flex-1">
            <Image src={web3} className=" rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>

          <div className="basis-1/2 flex-1">
            <Image src={web4} className=" rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>
        </div> 
         </section>
      </main>

    </div>
  )
}
